### ISSUE TITLE
While uploading directories, megatools gets stuck at 100% and upload speed drops to 0 Kbps

### ISSUE THREAD

**Issue by orkhanruth** [megous/megatools#360] opened 2018-07-10 08:18 UTC
Hello.
I've been experiencing this problem lately while trying to upload full directories. So my problem is that when I upload a directory, say it has 5 files on it,  it successfully uploads first two files, but when it uploads the third file and finishes doing so, it gets stuck at 100% and upload speed drops to 0 bytes/s. This is how the problem usually occurs, sometimes it gets stuck at the first file.

Edit: Here's how it exactly happens: https://i.imgur.com/k25rLZl.gifv

**Comment by megous** [comment] 2018-07-10 08:40
Can you please run the command with --debug http? You'll need a version from the master branch.

**Comment by orkhanruth** [comment] 2018-07-10 08:48
What is master branch? I tried running it on the version I usually use (1.9.98), but no change.

**Comment by megous** [comment] 2018-07-10 10:11
See https://megatools.megous.com/builds/

It's "1.9.99git" version. It has extra http option for --debug, that should be useful with debugging this.

**Comment by megous** [comment] 2018-07-10 12:42
Hmm, weird. Curl says it's uploaded, but will not return control to megatools.

What's the version of curl on your system?

**Comment by orkhanruth** [comment] 2018-07-10 13:28
I have "libcurl4-openssl-dev" installed (version: 7.55.1-1ubuntu2.5). I should also note that this problem I'm experiencing is only present for the last few days. Before that I was uploading everything just fine.

**Comment by megous** [comment] 2018-07-10 14:11
Ok. Let's give it some time and see if it will go away by itself too. :)

**Comment by kuboosoft** [comment] 2018-07-11 09:19
Same issue, in Fedora 1.9.98git  and 1.9.99git

**Comment by killown** [comment] 2018-07-11 22:15
same issue here

**Comment by albaldi** [comment] 2018-07-12 07:14
same here on archlinux

```
curl 7.60.0 (x86_64-pc-linux-gnu) libcurl/7.60.0 OpenSSL/1.1.0h zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.4) nghttp2/1.31.1                                                                                                                                                                                    
Release-Date: 2018-05-16
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
```
https://www.archlinux.org/packages/core/x86_64/curl/

tested with megatools 1.9.99git
here _PKGBUILD_ 

```
# Maintainer: Ondrej Jirman <megous@megous.com>

pkgname=megatools
pkgver=1.9.99git
pkgrel=2
pkgdesc="Command line client application for Mega.nz"
arch=('i686' 'x86_64' 'armv7h')
url="http://megatools.megous.com"
license=('GPL')
depends=('curl' 'glib2')
makedepends=('asciidoc')
source=("http://megatools.megous.com/builds/megatools-${pkgver}.tar.gz")
options=(!libtool)
sha256sums=('5c4fe323dedb223334aceb93833c95a18c20ce960e5a020e66cb8d01901108d4')

build() {
  cd "megatools-${pkgver}"

  ./configure --prefix=/usr

  make
}

package() {
  cd "megatools-${pkgver}"

  make install DESTDIR="${pkgdir}"
}

```

**Comment by megous** [comment] 2018-07-12 09:55
Ok. I can reproduce it on Arch Linux, too. It happens fairly consistently, but not predictably, every 5-10 files.

Mega.nz is sometimes not responding with the ID of the uploaded data that the client uses to create the node in the mega's filesystem.

**Comment by megous** [comment] 2018-07-12 10:15
I did a strace and it seems like a mega.nz issue. Sometimes it sends the ID, sometimes it does not and hangs on to the connection (if keepalive is set) in an incorrect state (without sending a response).

If I set Connection: close header, it just closes the connection right away after the data is uploaded, without even sending a response HTTP message.

Nothing I can do much about, I suppose. Someone needs to report this to mega.nz.

**Comment by TrueShutDown** [comment] 2018-07-12 16:39
on Ubuntu 18.04 Server same issue.

**Comment by megous** [comment] 2018-07-12 22:06
I've implemented parallel (multi-connection) chunked upload, and moved to a newer version of upload api and I'm testing it now. So far it works reliably without these lockups.

This should also help people on higher latency networks, speeding up the uploads.

It should also make uploads somewhat more reliable for really big files, because megatools will retry the chunk upload if it fails.

"A nice case" code paths work. It needs testing in various failing scenarios. Grab a master branch version and give it a try, if you're courageous.

**Comment by MCOfficer** [comment] 2018-07-12 23:19
master at 1d01ec4606304be1d1ae5df2501fb26ec86af5a3 appears to be working (ubuntu 18.04)

**Comment by igortrix** [comment] 2018-07-13 00:58
Thanks, fixed it.

is it possible to upload multi files/slots at once? I need to run 5-10 megacopy jobs for  max speed.

eg, I run 6x megacopy to upload at max speed / 100mbps (vnstat):
      r   rx:     3,05 Mbit/s  4946 p/s          tx:    99,62 Mbit/s  4802 p/s

**Comment by megous** [comment] 2018-07-13 06:47
It uploads multiple (8 at the moment) chunks of a bigger file at once. You'll notice only for files > 5-10MB or so. Test it to see. (just ignore the progress reporting by megatools, it's broken ATM)

**Comment by megous** [comment] 2018-07-13 08:34
Ok, it should be prepared for further testing. I'll release new version after this gets more feedback from more users.

**Comment by albaldi** [comment] 2018-07-13 14:34
used https://aur.archlinux.org/packages/megatools-git/ ( megatools-git-1.9.98.r66.ga13b99c-1-x86_64.pkg.tar.xz) on my Genuine Intel(R) CPU U2300 @ 1.20GHz

after uploading ~ 6GiB / 400 files no stuck so far, but:

| ParallelTransfers | Speed | CPU usage |
| --- | --- | --- |
| 1 | 350KiB/s - 1MiB/s | 3-6% |
| 8 | 3,5MiB/s - 4,5MiB/s | 45-55% |
| 16 | 7,5MiB/s - 8,9MiB/s | 90-115% |

Old 1.99git give 10MiB/s-15MiB/s at 5%CPU but get stuck :disappointed: 

- Is there a reason why _ParallelTransfers = 1_ don't give the same performance of old 1.99git?
- Is there a way to reduce CPU usage or increase speed at lower _ParallelTransfers_?
- is megatools CPU-bound on my old CPU?

thanks

**Comment by megous** [comment] 2018-07-13 14:56
Thanks for testing. Interesting insights there...

Load is probably because prior to recent changes, megatools did not use TLS for actual data transfers. Thanks for noticing this, I'll revert back to non-TLS data upload. That should help a lot.

For ParallelTransfers 1, the issue is that megatools will send new HTTP request for each 1MB of the input file. I'll have to verify that libcurl is re-using connections using keep-alive (despite being run from multiple threads), because otherwise it would have to set up new connection every 1 MB. (and for a first few MB it's every 128kB, 256kB, etc.) Eh. I can't choose chunk sizes, because that's mandated by the API.

**Comment by megous** [comment] 2018-07-13 15:07
Looking at the docs, the connections are not shared/re-used between multiple CURL easy handles, so that needs to be improved too.

Thankfully, in libcurl 7.57.0 there is a new sharing api that can be used in a threaded app with multiple easy handles.

https://ec.haxx.se/libcurl-sharing.html

cURL 7.57 is fairly new though, so some people on this thread will not be able to use this feature and will have slower performance.

**Comment by megous** [comment] 2018-07-13 15:13
I suspect dropping the TLS for data connections will help with most of the performance issues you're witnessing (establishing TLS connection is expenzive), if you can try your test again now, that would be helpful.

**Comment by albaldi** [comment] 2018-07-13 16:36
`megatools-git-1.9.98.r67.g6444f74-1-x86_64.pkg.tar.xz`
Test data : 2 files ~500MiB (1065864 according to **du**)
avr Speed calcolated using time megacopy:

1
```
real    42m3.473s
user    1m8.177s
sys     0m8.456s
```

default
```
real    5m5.197s
user    1m6.474s
sys     0m8.499s
```

16
```
real    2m23.851s
user    1m7.208s
sys     0m9.935s
```

max/avr CPU usage: _[ballpark](https://www.thefreedictionary.com/ballpark)_ estimate from **htop**

| ParallelTransfers | avr Speed | max CPU usage | avr CPU usage | Threads |
| --- | --- | --- | --- | --- |
| 1 | 422KiB/s | 5.4% | 4% | 3 |
| default | 3.49MiB/s | 40% | 30% | 10 |
| 16 |  7.41MiB/s | 80% | 45% | 18 |

why threads are _ParallelTransfers_ +2?
commit 6444f74550fc020b156231808a295fb9ff21f5ee improved cpu usage, but speed is still an issue. :disappointed: 


Will write a testscript tomorrow.

**Comment by megous** [comment] 2018-07-13 17:38
Connection cache is implemented. Default ParallelTransfers is changed to 5 for now. It's closer to the typical number of CPU cores and is better fo curl connection sharing.

Also I noticed Expect: 100-continue which caused unnecessary delay for each http request.

So hopefully now we'll be closer to the original performance.

**Comment by megous** [comment] 2018-07-13 18:01
I tested on single core VPS with  Intel(R) Xeon(R) CPU E5-2650L v4 @ 1.70GHz and I got between 6 and 28MiB/s, depending on the run and number of parallel transfers.

Top speed was CPU bound because load was 100%.

For 1 parallel transfer it maxes out on ~14 MiB/s and ~50% CPU load.

2 p.tr. = 18 MiB/s
3 p.tr. = 28 MiB/s

CPU can't keep up. Perhaps I can optimize CPU use now. :)

**Comment by megous** [comment] 2018-07-13 18:04
> why threads are ParallelTransfers +2?

https://github.com/megous/megatools/blob/master/lib/mega.c#L3010

**Comment by albaldi** [comment] 2018-07-14 00:01
I wrote this script for testing the speed
to run you need **megaput**, **megarm**, **[dd](https://linux.die.net/man/1/dd)**, **[paste](https://linux.die.net/man/1/paste)**, **[bc](https://www.gnu.org/software/bc/manual/html_mono/bc.html)**, **[time](https://linux.die.net/man/1/time)**, **[printf](https://linux.die.net/man/1/printf)**, **[seq](https://linux.die.net/man/1/seq)**
 
From the _time_ manual

> %e (Not in tcsh.) Elapsed real time (in seconds).
> %P Percentage of the CPU that this job got, computed as (%U + %S) / %E.


```
#!/bin/bash - 
set -o nounset                              # Treat unset variables as an error

SIZE="102400000"
FILE="tmp.bin"
RESULT="./tmp.result"

# megarc
USER="my@mail"
PSW="mypassword"
PARALLEL=16
MEGARC="./tmp.megarc"

dd if=/dev/urandom of="./$FILE" bs=4k iflag=count_bytes,fullblock count="$SIZE" &>/dev/null

for I in $(seq 1 "$PARALLEL") 
do
        printf '[Login]\nUsername = %s\nPassword = %s\n[Network]\nParallelTransfers = %s' "$USER" "$PSW" "$I" > $MEGARC
        printf '| %s | ' "$I" >> "$RESULT"
        /usr/bin/time -f '%e | %P |' -a -o "$RESULT" megaput --reload --config "$MEGARC" --no-progress "./$FILE" 
        megarm --config "$MEGARC" /Root/"$FILE"
done 

for i in $(cut -d\| -f3 $RESULT)
do
         printf " %s MiB/s |\n" $(echo "scale=2;"$SIZE"/"$i"/1024/1024" | bc -l) >> "$RESULT"-2
done 

printf '| Parallel | time | CPU | Speed |\n| --- | --- | --- | --- |\n' > report.txt
paste -d "" "$RESULT" "$RESULT"-2 >> report.txt

rm -f "./$FILE" "./$MEGARC" "$RESULT" "$RESULT"-2

```

edit the variables at the beginning and at it will create a _report.txt_ with a table you can post here 

My tables

| Parallel | time | CPU | Speed |
| --- | --- | --- | --- |
| 1 | 40.21 | 17% | 2.42 MiB/s |
| 2 | 23.83 | 28% | 4.09 MiB/s |
| 3 | 17.03 | 41% | 5.73 MiB/s |
| 4 | 12.14 | 58% | 8.04 MiB/s |
| 5 | 12.25 | 58% | 7.97 MiB/s |
| 6 | 11.24 | 64% | 8.68 MiB/s |
| 7 | 33.07 | 21% | 2.95 MiB/s |
| 8 | 10.03 | 73% | 9.73 MiB/s |
| 9 | 11.16 | 65% | 8.75 MiB/s |
| 10 | 47.65 | 15% | 2.04 MiB/s |
| 11 | 9.08 | 81% | 10.75 MiB/s |
| 12 | 8.03 | 92% | 12.16 MiB/s |
| 13 | 7.80 | 94% | 12.52 MiB/s |
| 14 | 8.10 | 92% | 12.05 MiB/s |
| 15 | 8.64 | 84% | 11.30 MiB/s |
| 16 | 8.06 | 92% | 12.11 MiB/s |

| Parallel | time | CPU | Speed |
| --- | --- | --- | --- |
| 1 | 76.25 | 9% | 1.28 MiB/s |
| 2 | 23.00 | 30% | 4.24 MiB/s |
| 3 | 17.66 | 40% | 5.52 MiB/s |
| 4 | 14.97 | 47% | 6.52 MiB/s |
| 5 | 14.10 | 50% | 6.92 MiB/s |
| 6 | 15.78 | 47% | 6.18 MiB/s |
| 7 | 23.32 | 31% | 4.18 MiB/s |
| 8 | 30.77 | 23% | 3.17 MiB/s |
| 9 | 8.40 | 89% | 11.62 MiB/s |
| 10 | 8.12 | 91% | 12.02 MiB/s |
| 11 | 15.36 | 47% | 6.35 MiB/s |
| 12 | 9.18 | 82% | 10.63 MiB/s |
| 13 | 8.82 | 86% | 11.07 MiB/s |
| 14 | 8.14 | 93% | 11.99 MiB/s |
| 15 | 14.48 | 52% | 6.74 MiB/s |
| 16 | 7.97 | 95% | 12.25 MiB/s |

| Parallel | time | CPU | Speed |
| --- | --- | --- | --- |
| 1 | 43.44 | 16% | 2.24 MiB/s |
| 2 | 20.52 | 34% | 4.75 MiB/s |
| 3 | 19.44 | 37% | 5.02 MiB/s |
| 4 | 19.12 | 37% | 5.10 MiB/s |
| 5 | 14.39 | 51% | 6.78 MiB/s |
| 6 | 14.38 | 52% | 6.79 MiB/s |
| 7 | 10.54 | 69% | 9.26 MiB/s |
| 8 | 12.11 | 61% | 8.06 MiB/s |
| 9 | 10.23 | 72% | 9.54 MiB/s |
| 10 | 24.33 | 30% | 4.01 MiB/s |
| 11 | 10.58 | 70% | 9.23 MiB/s |
| 12 | 9.12 | 83% | 10.70 MiB/s |
| 13 | 10.04 | 75% | 9.72 MiB/s |
| 14 | 8.46 | 90% | 11.54 MiB/s |
| 15 | 8.60 | 89% | 11.35 MiB/s |
| 16 | 7.83 | 97% | 12.47 MiB/s |

**Comment by V0rTeXbg** [comment] 2018-07-14 03:17
Can you provide fresh Windows builds? The latest ones are from May and the bug occurs. Me and many other people are not in position to compile it themselves.

**Comment by megous** [comment] 2018-07-14 03:48
With further optimizations, now I get ~50 MiB/s upload speed with 50% CPU load on a single core on the above mentioned cheap ass VPS with ParallelTransfers=5.

From a different data center (Italy) on the same speced VPS, I can reach > 60 MiB/s.

Prior to all these changes I could get max 27 MiB/s with 100% CPU load.

People on ARM64 should also see better numbers than before.

**Comment by megous** [comment] 2018-07-14 03:54
@albaldi You should be getting better numbers now, where previously the upload was CPU bound. Encryption is now 5 times faster on intel CPUs with aesni.

**Comment by megous** [comment] 2018-07-14 04:03
The script is not really optimal. With --reload you're measuring a latency of re-reading of your entire mega.nz filesystem. I'd drop --reload.

**Comment by megous** [comment] 2018-07-14 04:11
I tried running your script, but it reports speed 5.1 MB/s while if I run megaput directly with the same settings and progress reporting enabled it reports speed 27MiB/s.

**Comment by albaldi** [comment] 2018-07-14 07:51
`megatools-git-1.9.98.r72.g6996df9-1-x86_64.pkg.tar.xz
`

| Parallel | time | CPU | Speed |
| --- | --- | --- | --- |
| 1 | 36.64 | 8% | 2.66 MiB/s |
| 2 | 21.75 | 13% | 4.48 MiB/s |
| 3 | 16.79 | 18% | 5.81 MiB/s |
| 4 | 15.66 | 19% | 6.23 MiB/s |
| 5 | 13.55 | 23% | 7.20 MiB/s |
| 6 | 12.57 | 25% | 7.76 MiB/s |
| 7 | 14.24 | 22% | 6.85 MiB/s |
| 8 | 14.98 | 21% | 6.51 MiB/s |
| 9 | 7.43 | 44% | 13.14 MiB/s |
| 10 | 10.10 | 32% | 9.66 MiB/s |
| 11 | 9.57 | 34% | 10.20 MiB/s |
| 12 | 7.19 | 46% | 13.58 MiB/s |
| 13 | 7.81 | 41% | 12.50 MiB/s |
| 14 | 12.51 | 27% | 7.80 MiB/s |
| 15 | 8.94 | 41% | 10.92 MiB/s |
| 16 | 7.36 | 46% | 13.26 MiB/s |


6996df943e5135dd163df17735c1b5951899b49a really improved CPU usage :+1: 

@megous  script measure avrege speed, I too progress bar report value between 7-13 MiB/s
tried to running it in real-time, got bad performance :confused:  _htop_ showed less threads.

`sudo chrt -f 99 ./testmegatools.sh`


| Parallel | time | CPU | Speed |
| --- | --- | --- | --- |
| 1 | 41.30 | 7% | 2.36 MiB/s |
| 2 | 34.47 | 8% | 2.83 MiB/s |
| 3 | 20.29 | 14% | 4.81 MiB/s |
| 4 | 15.64 | 18% | 6.24 MiB/s |
| 5 | 14.15 | 21% | 6.90 MiB/s |
| 6 | 14.84 | 20% | 6.58 MiB/s |
| 7 | 15.58 | 20% | 6.26 MiB/s |
| 8 | 13.84 | 22% | 7.05 MiB/s |
| 9 | 31.26 | 10% | 3.12 MiB/s |
| 10 | 14.87 | 21% | 6.56 MiB/s |
| 11 | 12.21 | 26% | 7.99 MiB/s |
| 12 | 14.02 | 22% | 6.96 MiB/s |
| 13 | 12.35 | 25% | 7.90 MiB/s |
| 14 | 11.72 | 27% | 8.33 MiB/s |
| 15 | 11.11 | 29% | 8.78 MiB/s |
| 16 | 10.82 | 29% | 9.02 MiB/s |

**Comment by megous** [comment] 2018-07-14 08:04
@albaldi Results look good enough. You're back at 10-15MiB/s range you mentioned at the beginning, with multiple threads.

**Comment by albaldi** [comment] 2018-07-14 11:04
@megous can I ask for:

- option for set ParallelTransfers from cli
- option for set https instead of http https://github.com/megous/megatools/issues/360#issuecomment-404857977
- support for libcurl 7.57.0 https://github.com/megous/megatools/issues/360#issuecomment-404861524

thanks

**Comment by Tacioandrade** [comment] 2018-07-14 15:23
I'm going through the same problem, it reaches 100% and it locks up the backup. I am running on Windows Server 2012 and Windows Server 2012R2.

 .\megacopy.exe --local $BACKUP --remote $MEGADIR --debug
PS C:\Program Files\megatools> .\megacopy.exe  --debug --local $BACKUP --remote $MEGADIR
F /Root/backup/11/xxxxxxxxxxxxxxxxxxxxx.7z
-> [{
        "a": "u",
        "ssl": 0,
        "ms": 0,
        "s": 373809882,
        "r": 0,
        "e": 0
}]
<- [{
        "p": "http://gfs262n144.userstorage.mega.co.nz/ul/LWzzF865hRs9_QLwdCfmrscDiSY-BecjS8Hs6u32aikvpJvJB0tL-XDa5KVhIKpVweRsfSZJjZwDTbNMRnY_lQ"
}]
copying...: 100,00% - 356,5 MiB (373809882 bytes) of 356,5 MiB (0 bytes/s)s)

**Comment by Tacioandrade** [comment] 2018-07-14 16:09
Testing with version 1.9.99git-win64 and so far the problem has been solved. As soon as I do more testing, I give it back.

**Comment by Tacioandrade** [comment] 2018-07-14 18:05
@ViperCode7 Mega goes away?

**Comment by ViperCode7** [comment] 2018-07-14 19:16
:)) No, this whole thread in an **issue**... I ran into this issue, I thought it was because MEGA was fixing or updating something at their service. And I thought that the issue goes away, as many did in the past after a few days, the very same though megous posted way above...
> Ok. Let's give it some time and see if it will go away by itself too. :)

**Comment by megous** [comment] 2018-07-14 19:34
@albaldi 

> @megous can I ask for:
> 
>     option for set ParallelTransfers from cli

I don't see much value. Expected use case is that unless you have an issue with the default setting, you'll try what works best for your connection, put it into .megarc and forget about it ever after. It's not something you want to set for each transfer.

>     option for set https instead of http #360 (comment)

It's pointless for a data connection, which is both encrypted and authenticated with a MAC. TLS was always used for the API connection, where it has value.

>     support for libcurl 7.57.0 #360 (comment)

Megatools support this and newer and oler version of megatools.

**Comment by megous** [comment] 2018-07-14 19:40
For everyone, if you use distro with libcurl < 5.57.0, you'll see some performance issues for a simple reason that curl will close and re-establish connection for each 1MB chunk of the uploaded file. You'll get most of the benefits only if you upgrade libcurl and re-compile megatools.

@ViperCode7 Re: oscillation

Progress reporting code in that version is broken. It's fixed in the master.

**Comment by extensionsapp** [comment] 2018-07-17 14:16
@megous Hello. I install megatools:
```
        VER=`lsb_release -cs`
        sed -i s/${VER}/stretch/g /etc/apt/sources.list
        aptitude update
        aptitude -y -q install megatools
        sed -i s/stretch/${VER}/g /etc/apt/sources.list
        aptitude update
```

How to update to 1.9.99 (fix this problem)?

**Comment by megous** [comment] 2018-07-17 15:07
@extensionsapp Check out the README file.

**Comment by extensionsapp** [comment] 2018-07-17 19:47
@megous error.

```
~/megatools# ./autogen.sh --prefix=$HOME/.local --disable-docs
./autogen.sh: 11: ./autogen.sh: autoreconf: not found
```

```
        aptitude update
        aptitude -y -q install build-essential libglib2.0-dev libssl-dev libcurl4-openssl-dev
        git clone git://megous.com/megatools
        cd megatools
        ./autogen.sh --prefix=$HOME/.local --disable-docs
        make -j4
        make install
```

**Comment by mdrzn** [comment] 2018-07-18 07:18
I've been using the 1.9.94 for almost two years now, and it always worked flawlessy without my intervention.
I've noticed lately that it gets stuck at 100% uploads, without closing the connection.

I tried updating to 1.9.98, brand new MEGA account, uploaded one file thru browser and it works, when I try to upload via debian it also hangs at 100% (always at 100%, file is about 90MB, takes 3 secs to upload it then it gets stuck).

**Comment by megous** [comment] 2018-07-18 21:00
Ok, let's call this fixed.

**Closed by megous** 2018-07-18 21:00 UTC
Labels: needs user testing

**Comment by orkhanruth** [comment] 2018-07-18 21:56
When will you release a fixed stable version?

**Comment by megous** [comment] 2018-07-18 22:51
See #362
