### ISSUE TITLE
Not consistent uploading speed 

### ISSUE THREAD

**Issue by Pinhcy** [megous/megatools#365] opened 2018-07-19 07:39 UTC
I have just upgraded to 1.10.0-rc1 and have noticed that the speed for uploading via megacopy is extremely sporadic, its jumping from 0 bytes to various other speeds and is not uploading at a consistent speed. 

Uploading a file inside a directory which is 25gbs in size.

**Comment by Pinhcy** [comment] 2018-07-19 07:56
Here is error I am getting during uploads.

`ERROR: Upload failed for "FILE": Data upload failed: Upload transfer failed: Chunk upload failed: CURL error: Couldn't connect to server`

**Comment by megous** [comment] 2018-07-19 08:58
What value are you using for ParallelTransfers? Default?

**Comment by megous** [comment] 2018-07-19 09:00
This might happen if mega's upload server is rejecting connections.

**Comment by megous** [comment] 2018-07-19 09:03
I should probably try not to re-connect immediately but with some exponential backoff, otherwise re-upload counter may terminate the transfer too soon.

**Comment by megous** [comment] 2018-07-19 09:21
You may try setting lower value for ParallelTransfers. Something like 2 or 3, if that helps.

**Comment by Pinhcy** [comment] 2018-07-19 09:51
Alright I have changed it to 3 and seems to have allowed me to finish an upload! The progress speed indicator still is very sporadic.

**Comment by megous** [comment] 2018-07-19 10:03
Mega, suggesting to use 6 parallel connections and then dropping half of them. :)

**Comment by Pinhcy** [comment] 2018-07-19 10:50
This is new error I am getting 

`ERROR: Upload failed for "file": Data upload failed: Upload transfer failed: Server returned error code ERATELIMIT
`
Strange thing is on the third attempt at uploading the file it worked.

**Comment by megous** [comment] 2018-07-19 10:58
Yeah, looks like mega's rate limitting something. BTW, are you running multiple megatools commands in parallel?

**Comment by Pinhcy** [comment] 2018-07-19 11:00
Just one command 

megacopy  --local PATH/"FILE" --remote /Root

**Comment by megous** [comment] 2018-07-19 12:50
I improved the chunk upload retry backoff, so ERATELIMIT should not be an issue anymore, and hopefully uploads will be more reliable.

**Comment by Pinhcy** [comment] 2018-07-19 13:55
ERATELIMIT issue has now gone, have successfully uploaded 3 large files with no retries.

**Comment by albaldi** [comment] 2018-07-19 21:31
`megatools-git-1.10.0.rc2.r0.gfc8adce-1-x86_64.pkg.tar.xz` upload is slow. 5-7MiB
with `megatools-git-1.9.98.r86.g2cb5e29-1-x86_64.pkg.tar.xz` (2cb5e294b475ac97fabc5c37657e2254ae6eb7c7) I was able to go to 9-12MiB

**Comment by albaldi** [comment] 2018-07-19 21:49
can you revert bd18f30cdd72646dc71f8618cf757433212114b0 ? or at least revert from 5 to 16. I had no problem before with 16.

**Comment by megous** [comment] 2018-07-19 22:39
I'll consider that. But that has an unfortunate effect of curl closing the API connection during almost all transfers, and that's costly to re-connect, because it's TLS.

**Comment by albaldi** [comment] 2018-07-19 22:57
I'm fine with default 3, just like to go over 5 if I'd like.

**Comment by Pinhcy** [comment] 2018-07-20 05:18
Have started getting ERATELIMIT and EARGS errors, uploads are not finishing.

**Comment by megous** [comment] 2018-07-20 09:06
EARGS, I haven't seen that one yet. I need the entire error message though.

**Comment by Pinhcy** [comment] 2018-07-20 09:28
I have been trying to reproduce the EARGS error but have been consistently getting the ERATELIMIT error only at the moment. Strange and I did manage to upload 3 files fine in a row.  

` Upload failed for ''FILE": Data upload failed: Upload transfer failed: Server returned error code ERATELIMIT
`

Have received this after 5 retries. EARGS error has not returned since last night.

**Comment by megous** [comment] 2018-07-20 09:36
I wonder what is mega server actually limiting, since the official SDK uses up to 20 parallel transfers. Bah. You can try --debug tman if it will show some strange pattern before the EARGS error.

**Comment by megous** [comment] 2018-07-20 09:41
Anyway, I think I know what the issue is with ERATELIMIT. Rate limit is for all transfers not just those that failed. Megatools now only throttles the failed ones. EARGS is a bit more mysterious though.

**Comment by megous** [comment] 2018-07-20 09:46
EARGS can be debugged with --debug api.

**Comment by Pinhcy** [comment] 2018-07-20 09:51
Seems I cant reproduce the EARGS error.

**Comment by Pinhcy** [comment] 2018-07-20 09:52
Just getting a heap of this with --debug 

`
10264739437269: M: chunk 1103 failed, re-queueing
10264739437283: M: chunk 1106 pushed to worker
10264739437318: W: started for chunk 1106
`

**Comment by megous** [comment] 2018-07-20 10:01
Yes, ignore the ERATELIMIT for now. I think I know where it's comming from.

**Comment by albaldi** [comment] 2018-07-20 23:27
I just got a ERATELIMIT , probably caused by uploading lots of small file (<100KiB)

**Comment by megous** [comment] 2018-07-22 22:12
ERATELIMIT is not really a rate limit it's EFAIL. Error -4 just has different meanings for API calls and for upload servers. When mega returns it the error is not recoverable. You can just re-upload the whole file.

Mega's servers are broken when dealing with parallel uploads of 16MiB chunks. More than 2-3 parallel uploads and it starts failing with EFAIL. I can do 16 parallel uploads of old-style 1MiB chunks all day without an issue. Probably some race condition or whatever on their side.

At least I don't get any stalls with 0 B/s anymore. It sometimes happens, but it is not infinite, but takes ~10s to resolve by itself.

Also mega sometimes decides for the fun of it or whatever, to accept all upload transfers and just not return the upload token for creating a mega filesystem node. It even has a special case in their official SDK. In this case, megatools will just re-upload everything.

So I guess that's it. I'll release 1.10.0 with my changes and see what happens.

**Comment by megous** [comment] 2018-07-22 22:49
Should be all fixed in 1.10.0. If it hangs for a bit, just wait. It should err out or recover within a minute or so.

**Closed by megous** 2018-07-22 22:49 UTC
